### ISSUE TITLE
Boolean input prints label and hint twice (v 3.1)

### ISSUE THREAD

**Issue by glampr** [mjbellantoni/formtastic-bootstrap#126] opened 2015-03-26 18:04 UTC
Boolean inputs print the label twice, once from ```bootstrap_wrapping``` before the checkbox and once after the label from ```label_text_with_embedded_checkbox```.
The one from ```bootstrap_wrapping``` needs not be included for boolean input.
The same happens for the hint, it's printed from ```bootstrap_wrapping``` and again included explicitly in ```to_html```.

**Comment by fredngo** [comment] 2015-03-30 09:09
I believe this is a duplicate of https://github.com/mjbellantoni/formtastic-bootstrap/issues/118, which has been fixed, but the gem is still awaiting a new release (https://github.com/mjbellantoni/formtastic-bootstrap/issues/124)

**Comment by sodabrew** [comment] 2015-07-19 17:07
Done! https://rubygems.org/gems/formtastic-bootstrap/versions/3.1.1

**Closed by sodabrew** 2015-07-19 17:07 UTC

**Comment by fredngo** [comment] 2015-07-21 19:36
Thanks!
