### ISSUE TITLE
double label for :as => boolean

### ISSUE THREAD

**Issue by optimum-dulopin** [mjbellantoni/formtastic-bootstrap#118] opened 2015-01-13 01:12 UTC
when you use
        <%= f.input :my_field, :as => :boolean, :label => 'xxxxxxx' %>

it double the label before and after the checkbox

so it renders :

<div id="my_model_my_field_input" class="boolean input optional checkbox">
  <span class="form-label">
    <label for="my_model_my_field" class=" control-label">
      xxxxxxx
    </label>
  </span>
  <span class="form-wrapper">
    <input type="hidden" value="0" name="my_model[my_field]">
    <label for="my_model_my_field" class=" control-label">
      <input type="checkbox" value="1" name="my_model[my_field]" id="my_model_my_field">xxxxxxx
    </label>
  </span>
</div>

**Comment by sodabrew** [comment] 2015-01-13 01:42
Is this with formtastic-bootstrap 3.1.0?

**Comment by optimum-dulopin** [comment] 2015-01-13 02:20
yes

**Comment by tijmenb** [comment] 2015-01-13 21:22
I'm running into this as well. Seems to be caused by https://github.com/mjbellantoni/formtastic-bootstrap/pull/94, specifically https://github.com/jtomaszewski/formtastic-bootstrap/commit/d212909bb101d78f134218d2274d3da45c02fc01#diff-1 @jtomaszewski can we keep `checkbox_wrapping` there and keep compatibility with horizontal forms at the same time? 

This is the output of a `f.input :accept_tos, as: :boolean`:

```html
<div class="boolean input required checkbox" id="user_signup_accept_tos_input">
  <span class="form-label">
    <label for="user_signup_accept_tos" class=" control-label">
      <p>I accept the ToS</p>
    </label>
  </span>
    
  <span class="form-wrapper">
    <input type="hidden" name="user_signup[accept_tos]" value="0">
    <label for="user_signup_accept_tos" class=" control-label">
      <input type="checkbox" name="user_signup[accept_tos]" id="user_signup_accept_tos" value="1">
      <p>I accept the ToS</p>
    </label>
  </span>
</div>
```

**Comment by optimum-dulopin** [comment] 2015-01-16 01:42
hi,
is there anything we can do before this issue is corrected ?

**Comment by jtomaszewski** [comment] 2015-01-16 11:39
Fixed in 16cb074ab56c2a71bc76956ff44f4d85c3063473 .

**Closed** 2015-01-16 11:38 UTC

**Comment by fredngo** [comment] 2015-05-21 00:54
Any chance for a 3.1.1 rubygem release?

**Comment by tibbon** [comment] 2015-07-08 18:23
+1

**Comment by bashantad** [comment] 2015-07-15 02:06
We are waiting for version 3.1.1 release.

**Comment by jtomaszewski** [comment] 2015-07-19 14:06
@mjbellantoni , could you make the release?

**Comment by sodabrew** [comment] 2015-07-19 17:07
Done! https://rubygems.org/gems/formtastic-bootstrap/versions/3.1.1

**Comment by mjbellantoni** [comment] 2015-07-20 02:46
Thanks, Aaron!

-m

**Comment by ryanttb** [comment] 2015-07-23 17:41
Thank you! I just hit this and happy to see that it was resolved so quickly so all I had to do was update my gem.
